### ISSUE TITLE
1.0.0 beta3 crashes Fabric 1.20.1 server on startup

### ISSUE THREAD

**Issue by kbsmilk** [opekope2/LiLaC#8] opened 2023-12-12 03:09 UTC
Repro:
1. Create a new server instance with these specs: 
- Fabric loader 0.15.1
- Minecraft 1.20.1
- Java 17 or 18
2. Add the mods:
- Fabric api 0.91.0
- fabric-language-kotlin-1.10.16+kotlin.1.9.21
- Lilac 1.0.0 beta 3
3. Launch the server and it should crash very early.

I have not explicitly tested a server on Java 18 with these exact mods. Lilac crashed the server on another machine, running Java 18 and a large modpack.

[latest.log](https://github.com/opekope2/LiLaC/files/13643221/latest.log)

**Comment by opekope2** [comment] 2023-12-12 12:23
Duplicate of #6, but with Fabric loader. The issue is that I use client code on server side. I already have a fix on the `dev` branch, will push with the next update (prob early 2024)

**Closed as not planned by opekope2** 2023-12-12 12:23 UTC
